services:
    db-postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER:-postgres}" -d "$${POSTGRES_DB:-postgres}" -h localhost || exit 1' ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
        networks:
            logira-network:
                aliases:
                    - postgres

    postgre-panel:
        image: adminer:5
        restart: unless-stopped
        depends_on:
            db-postgres:
                condition: service_healthy

    db-redis:
        image: redis:7.2-alpine
        restart: unless-stopped
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: >
            redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec
        healthcheck:
            test: [ "CMD-SHELL", 'redis-cli -a "$$REDIS_PASSWORD" ping | grep PONG' ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 5s
        volumes:
            - redis_data:/data
        networks:
            logira-network:
                aliases:
                    - redis

    db-migrate:
        build: ./backend
        restart: "no"
        command: alembic upgrade head
        exclude_from_hc: true
        depends_on:
            db-postgres:
                condition: service_healthy
        environment:
            - DATABASE_URL=${DATABASE_URL}
        networks:
            logira-network:
                aliases:
                    - migrate

    backend:
        build: ./backend
        expose:
            - "8000"
        restart: always
        depends_on:
            db-postgres:
                condition: service_healthy
            db-redis:
                condition: service_healthy
            db-migrate:
                condition: service_completed_successfully
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - ALGORITHM=${ALGORITHM}
            - N8N_URL=${N8N_URL}
            - N8N_KEY=${N8N_KEY}
            - SECRET_KEY=${SECRET_KEY}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
            - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
            # - USER_SECRET_KEY=${USER_SECRET_KEY}
            # - INTEGRATION_SECRET_KEY=${INTEGRATION_SECRET_KEY}
            # - BUSINESS_INTEGRATION_SECRET_KEY=${BUSINESS_INTEGRATION_SECRET_KEY}
            # - USER_ACCESS_TOKEN_EXPIRE_MINUTES=${USER_ACCESS_TOKEN_EXPIRE_MINUTES}
            # - USER_REFRESH_TOKEN_EXPIRE_DAYS=${USER_REFRESH_TOKEN_EXPIRE_DAYS}
            # - INTEGRATION_TOKEN_EXPIRE_DAYS=${INTEGRATION_TOKEN_EXPIRE_DAYS}
            # - BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES=${BUSINESS_INTEGRATION_TOKEN_EXPIRE_MINUTES}

        networks:
            logira-network:
                aliases:
                    - backend
            n8n-network:
                aliases:
                    - logira_backend

volumes:
    postgres_data:
    redis_data:

networks:
    logira-network:
        external: true
    n8n-network:
        external: true
